fix: streaming-articles 404 error for missing files on s3
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found